version: '2.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    ports:
     - 9200:9200
     - 9300:9300
    environment:
     - DISCOVERY_TYPE=single-node
     - ES_JAVA_OPTS=-Xms750m -Xmx750m

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.8
    ports:
     - 5601:5601
    environment:
      #SERVER_NAME: kibana.example.org
     - ELASTICSEARCH_URL=http://elasticsearch:9200
